// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnuSxo65H7nbaskmWAb7IqWmp_TXsMdg',
    appId: '1:262671604101:android:b08624860587e3b9ab4cec',
    messagingSenderId: '262671604101',
    projectId: 'automato-7ed8e',
    databaseURL: 'https://automato-7ed8e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automato-7ed8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CDlDaznpcXqUDN88wKqQTTgknb0YUdw',
    appId: '1:262671604101:ios:961b798cdb19e2fbab4cec',
    messagingSenderId: '262671604101',
    projectId: 'automato-7ed8e',
    databaseURL: 'https://automato-7ed8e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automato-7ed8e.firebasestorage.app',
    androidClientId: '262671604101-ae31mj436lakofj8m69e8bbvgvpsj6pa.apps.googleusercontent.com',
    iosClientId: '262671604101-kq73vjjaftnnesl1prrifiinm7rt1k8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.autmApplication02',
  );
}
